### ISSUE TITLE
mute tab on startup

### ISSUE THREAD

**Issue by tommasodinoia** [Unipisa/TeamsCarousel#3]
Ciao Antonio, visto che l'estensione viene usata per sfruttare Chrome semplicemente per visualizzare le immagini, potrebbe essere utile avere la possibilità di mettere in Mute il tab all'avvio. Tutto il codice necessario dovrebbe essere qui
https://github.com/trmcnvn/chrome-tab-mute/blob/master/background.js

**Comment by cisterni** [comment]
Ho integrato la possibilità di silenziare il tab dal menu. Devo testarlo per poi metterlo nel package

**Comment by cisterni** [comment]
La funzione è attiva nella release appena pubblicata
