### ISSUE TITLE
Does not scroll past first participant

### ISSUE THREAD

**Issue by fph** [Unipisa/TeamsCarousel#7]
Hello! I tried the extension for Chrome on Windows this morning, during a lecture of another course.
The extension correctly selects the first participant, but then it stops there, with the first participant pinned, only opening and closing the same menu. It looks like it is trying to open a menu automatically and it fails. Here is a video displaying the bug:
http://pages.di.unipi.it/fpoloni/videolezioni/tmp/Carousel%20bug.mp4

System info: Chromium Version 84.0.4136.0 (Developer Build) (64-bit) on Windows 10 Pro build 18363. Everything is localized in English, in case it's a bug with localized menu entries.

**Comment by fph** [comment]
For the record, I get the same behavior with the official Chrome 81.0.4044.138 (official build) and with Edge (83.0.478.28 (Official build) beta (64 bit)). I could not get the extension working at all, on Windows 10, with any of the supported browsers.

**Comment by cisterni** [comment]
I'm reviewing the code that switches among participants, also because the hand-up feature has corrupted the functioning.

**Comment by cisterni** [comment]
Updated the current version that should fix the issue here.
