### ISSUE TITLE
Some feedback for Chrome installation instructions

### ISSUE THREAD

**Issue by annabigatti** [Unipisa/TeamsCarousel#8]
Per installare l'estensione manualmente procedere come segue:

- Scompattare il file zip in una cartella nel computer
--- in packages/   (meglio specificare)
---    ci sono due file zip in packages nello zip che ho scaricato da github:
---      TeamsCarousel.zip
---      TeamsCarousel-0.1.zip
---    e' voluto?

- in un tab Chrome navigare a chrome://extensions
--- abilitare la "ModalitÃ  sviluppatore / Developer mode" selezionando il controllo in alto a destra
--- selezionare l'operazione "Carica estensione non pacchettizzata / Load unpacked"
---   specificare anche qualcosa tipo:
---     andare su  "src"  e cliccare  "Select"
---   (io mi aspettavo di dover fare Select di un file, e non trovavo quale)

Una volta attivata l'estensione:
--- basta caricarla, o no?  non trovo un'attivazione da fare
--- non ho ancora provato con cavie umane, ma direi che risulta installato
- in una call premere l'icona dello strumento e play

**Comment by cisterni** [comment]
Va usato solo l'ultimo zip (ho lasciato la versione precedente just in case).
Chiarisco la parte per chrome
Una volta caricata viene abilitata. Nota che la funzione della mano alzata ha rotto il sistema e conto di rilasciare a breve un aggiornamento per risolvere il problema.

**Comment by annabigatti** [comment]
grazie
Anna

Quoting cisterni <notifications@github.com>:

> Va usato solo l'ultimo zip (ho lasciato la versione precedente just in case).
> Chiarisco la parte per chrome
> Una volta caricata viene abilitata. Nota che la funzione della mano  
> alzata ha rotto il sistema e conto di rilasciare a breve un  
> aggiornamento per risolvere il problema.

**Comment by cisterni** [comment]
Ho aggiornato la documentazione (e anche il pacchetto)
